openapi: 3.0.0
info:
  title: Invoice API
  version: 1.0.0
paths:
  /invoices:
    get:
      summary: List invoices
      description: Retrieve all invoices in the system.
      responses:
        '200':
          description: A list of invoices.
    post:
      summary: Create an invoice
      description: Generate a new invoice.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: Invoice created.

  /invoices/{id}:
    get:
      summary: Get invoice by ID
      description: Retrieve a specific invoice by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invoice details.
components:
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        amount:
          type: number
        status:
          type: string
