openapi: 3.0.0
info:
  title: Invoice API
  version: 2.0.0
paths:
  /invoices:
    get:
      summary: List invoices
      description: Fetch all invoices with detailed breakdown.
      responses:
        '200':
          description: List of invoices with updated schema.
    post:
      summary: Create an invoice
      description: Create an invoice with tax breakdown and updated schema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '201':
          description: Invoice created.

  /invoices/{id}:
    get:
      summary: Get invoice by UUID
      description: Retrieve invoice using UUID instead of string.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Invoice with new schema format.
components:
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
        subtotal:
          type: number
        tax:
          type: number
        total:
          type: number
        state:
          type: string
