openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticate a user and return a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful with JWT.
  
  /auth/logout:
    post:
      summary: User logout
      description: Invalidate the user session or token.
      responses:
        '204':
          description: Logout successful.

  /auth/refresh:
    post:
      summary: Refresh token
      description: Obtain a new access token using a refresh token.
      responses:
        '200':
          description: New token issued.
