openapi: 3.0.0
info:
  title: Role and Permission API
  version: 1.0.0
paths:
  /roles:
    get:
      summary: List roles
      description: Retrieve all defined roles.
      responses:
        '200':
          description: List of roles.
    post:
      summary: Create role
      description: Define a new role with associated permissions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '201':
          description: Role created.

  /roles/{id}/permissions:
    get:
      summary: Get role permissions
      description: List all permissions associated with a specific role.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role permissions list.
components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        permissions:
          type: array
          items:
            type: string
