openapi: 3.0.0
info:
  title: User Profile API
  version: 1.0.0
paths:
  /users:
    get:
      summary: List users
      description: Retrieve all registered user profiles.
      responses:
        '200':
          description: A list of users.
    post:
      summary: Create user profile
      description: Register a new user in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created.

  /users/{id}:
    get:
      summary: Get user by ID
      description: Fetch a specific user's profile details.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile.
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        fullName:
          type: string
